name: Build and Push WAF Backend

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: waf_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      # Step 3: Write environment file
      - name: Write .env file
        run: |
          echo "DB_USER=postgres" >> ./Backend/.env
          echo "DB_PASSWORD=postgres" >> ./Backend/.env
          echo "DB_HOST=localhost" >> ./Backend/.env
          echo "DB_PORT=5432" >> ./Backend/.env
          echo "DB_NAME=waf_db" >> ./Backend/.env
          echo "DB_SSLMODE=disable" >> ./Backend/.env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> ./Backend/.env

      # Step 4: Install dependencies & Build the Go application
      - name: Build the application
        run: |
          cd Backend
          go mod tidy
          go build -o backend ./cmd

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t natnaelcrypto/waf-backend:latest -f Backend/Dockerfile .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u natnaelcrypto -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push natnaelcrypto/waf-backend:latest
