name: Build and Push CNN_API Docker Image

on:
  push:
    branches:
      - main  # Run workflow when pushing to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t natnaelcrypto/cnn_api:latest -f ML/Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: |
          docker login -u natnaelcrypto -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push natnaelcrypto/cnn_api:latest
