version: "3.8"

services:
  backend:
    image: natnaelcrypto/waf-backend:latest
    container_name: waf-backend
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: waf_db
      DB_SSLMODE: disable
    ports:
      - "8484:8484"

  db:
    image: postgres:latest
    container_name: waf-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
